homeassistant: true

mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
  user: "!ENV MQTT_USER"
  password: "!ENV MQTT_PASSWORD"

serial:
  port: /dev/ttyUSB0

frontend:
  port: 8080

permit_join: true

advanced:
  log_level: info
  network_key: GENERATE
